services:
  tgmgr:
    image: ghcr.io/rphhhh-ubt/fastly_flowers:latest
    container_name: mybot
    restart: unless-stopped
    env_file:
      - .env
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./data:/data
      - ./sessions:/app/sessions
      - ./logs:/app/logs
      - ./avatars:/app/avatars:ro
      - ./channel_avatars:/app/channel_avatars:ro
      - /etc/machine-id:/etc/machine-id:ro
    security_opt:
      - no-new-privileges:true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bd.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: