# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import asyncio
import json
import random
import typing
import aiogram
import aiogram.Bot
import aiogram.types
import aiogram.types.BufferedInputFile
import telethon
import telethon.errors
import telethon.errors.FloodWaitError
import telethon.errors.RPCError
import telethon.tl
import telethon.tl.functions
import telethon.tl.functions.messages
import aiogram.types.InlineKeyboardMarkup
import aiogram.types.InlineKeyboardButton
import tasks
import tasks.base_executor
import app
import app.db
import app.telegram_client
import config

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

