# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import asyncio
import random
import telethon
import telethon.errors
import telethon.errors.FloodWaitError
import telethon.errors.FloodError
import telethon.errors.ChannelPrivateError
import telethon.errors.ChatAdminRequiredError
import telethon.errors.AuthKeyUnregisteredError
import telethon.errors.UsernameNotOccupiedError
import telethon.errors.UsernameInvalidError
import telethon.errors.ChannelInvalidError
import telethon.errors.RPCError
import telethon.tl
import telethon.tl.functions
import telethon.tl.functions.channels
import app
import app.telegram_client
import app.db

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

