# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import asyncio
import random
import time
import json
import traceback
import telethon
import telethon.types
import telethon.TelegramClient
import telethon.tl
import telethon.tl.functions
import telethon.tl.functions.channels
import app
import app.telegram_client
import telethon.tl.types
import telethon.tl.types.PeerChannel
import telethon.tl.types.ChatReactionsAll
import telethon.tl.types.ChatReactionsSome
import telethon.tl.types.ChatReactionsNone
import telethon.tl.functions.messages
import telethon.errors
import telethon.errors.UserNotParticipantError
import telethon.errors.ChannelsTooMuchError
import telethon.errors.ChannelPrivateError
import telethon.errors.UserAlreadyParticipantError
import telethon.errors.ChatAdminRequiredError
import telethon.errors.FloodWaitError
import aiogram
import aiogram.fsm
import aiogram.fsm.context
import app.db
import telethon.errors.rpcerrorlist
import hashlib

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

